# Generated by Django 3.1.1 on 2020-09-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.CharField(default='user1', max_length=100),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='username',
            field=models.CharField(help_text='@your_name', max_length=100),
        ),
    ]
