# Generated by Django 3.1.1 on 2020-09-10 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20200910_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
